[project]
name = "img2pc"
version = "0.1.0"
description = "Simple image to point cloud model with GATr"
authors = [
    {name = "guest400123064", email = "wangy49@alumni.upenn.edu"},
    {name = "M4D-SC1ENTIST", email = "xiatao.sun@yale.edu"}
]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ezgatr @ file:///home/catcat/projects/ezgatr",
    "transformers (>=4.48.3,<5.0.0)",
    "pillow (>=11.1.0,<12.0.0)",
    "iopath (>=0.1.10,<0.2.0)",
    "fvcore (>=0.1.5.post20221221,<0.2.0)",
    "numpy (<2.0.0)",
    "pytorch3d @ https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py310_cu121_pyt240/pytorch3d-0.7.8-cp310-cp310-linux_x86_64.whl",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
ezgatr = {develop = true}

[tool.poetry.group.dev.dependencies]
bpython = "^0.25"
ipykernel = "^6.29.5"
seaborn = "^0.13.2"
